### ISSUE TITLE
Snippets installed properly but not enabled in neovim

### ISSUE THREAD

**Issue by boardfish** [jvanja/vim-bootstrap4-snippets#1]
I installed this with Vundle, maybe intending to learn Vimscript and update it for the beta. By grepping the bundle directory, I could see that the plugin had installed correctly. However, if I edit a blank html file and try to complete various shortcuts such as `btn` and `htmlb4`, the keywords aren't found and expanded by Snipmate.

**Comment by jvanja** [comment]
@boardfish I just pushed an update that should fix this! 
Please let me know if it worked and thanks for reporting the issue!

**Comment by boardfish** [comment]
Yep, that's fine. A simple :PluginUpdate with Vundle sorted it.
