### ISSUE TITLE
I am not getting suggestions as shown in gif.

### ISSUE THREAD

**Issue by aasutossh** [jvanja/vim-bootstrap4-snippets#3]
when typing htmlb4 I am not getting suggestions as shown in the image. I installed snipMate and UltiSnips too.

**Comment by jvanja** [comment]
@DrDonkey Are you editing an HTML file? The snippets are triggered only within an appropriate file type. Also, are you successfully triggering any other Ultisnips snippet? You can first try with something default from Ultisnips to make sure the plugin is functioning and then try the bootstrap4.

**Comment by aasutossh** [comment]
I went to ultisnips github, tried editing python. tried class keyword but the pop dones't come up. I can tab to expand though. But that isn't the main reason I installed, I need popup suggestions.
I think its ultisnips problem.

**Comment by jvanja** [comment]
It sounds like it's something related to ultisnips. Closing this thread.

**Comment by aasutossh** [comment]
I opened issue in their repo too.
Do you need youcompleteme and snipmate too?

**Comment by codias** [comment]
i have the same issue. If you use youcompleteme and vim-bootstrap4-snippets they both use the "TAB" key to select, but i don't know how to change the keymapping in youcompleteme or vim-bootstrap4-snippets.
Tried to change the keymapping for utilsnips to not use "TAB"  but also failed.
Any help or hint on how to change the mapping would be great.
thx

**Comment by codias** [comment]
" Trigger configuration. Do not use tab if you use https://github.com/Valloric/YouCompleteMe.
" let g:UltiSnipsExpandTrigger="tab" change this to something else like "c-j" add the <> to expr.
" let g:UltiSnipsJumpForwardTrigger="c-b"
" let g:UltiSnipsJumpBackwardTrigger="c-z"

This works for me with youcompleteme.
https://github.com/SirVer/ultisnips
