### ISSUE TITLE
Same snippet files in 3 different folders

### ISSUE THREAD

**Issue by toBfree** [jvanja/vim-bootstrap4-snippets#4]
Hi jvanja, 
Thank you for your wonderful vim plugin, I am currently improving it in a fork to extend the bootstrap snippets to do data visualization with javascript snippets code.
My question is: why do you have the same snippet files in 3 different folders (html, snippet, Utilsnips) ?

**Comment by jvanja** [comment]
> Hi jvanja,
> Thank you for your wonderful vim plugin, I am currently improving it in a fork to extend the bootstrap snippets to do data visualization with javascript snippets code.
> My question is: why do you have the same snippet files in 3 different folders (html, snippet, Utilsnips) ?

The different folders are for different Vim snippets plugins like  UltiSnips and snipMate.
